flowchart LR
    BASE_BLUE[BASE_BLUE] --- LANE_TOP[LANE_TOP]
    BASE_BLUE[BASE_BLUE] --- LANE_MID[LANE_MID]
    BASE_BLUE[BASE_BLUE] --- LANE_BOTTOM[LANE_BOTTOM]
    LANE_MID[LANE_MID] --- BRIDGE_MID[BRIDGE_MID]
    RIVER_TOP[RIVER_TOP] --- BRIDGE_MID[BRIDGE_MID]
    BRIDGE_MID[BRIDGE_MID] --- RIVER_BOTTOM[RIVER_BOTTOM]
    LANE_TOP[LANE_TOP] --- RIVER_ENTRY_BLUE_TOP_LANE[RIVER_ENTRY_BLUE_TOP_LANE]
    RIVER_ENTRY_BLUE_TOP_LANE[RIVER_ENTRY_BLUE_TOP_LANE] --- RIVER_TOP[RIVER_TOP]
    LANE_MID[LANE_MID] --- RIVER_ENTRY_BLUE_MID_TOP[RIVER_ENTRY_BLUE_MID_TOP]
    RIVER_ENTRY_BLUE_MID_TOP[RIVER_ENTRY_BLUE_MID_TOP] --- RIVER_TOP[RIVER_TOP]
    LANE_TOP[LANE_TOP] --- RIVER_ENTRY_RED_TOP_LANE[RIVER_ENTRY_RED_TOP_LANE]
    RIVER_ENTRY_RED_TOP_LANE[RIVER_ENTRY_RED_TOP_LANE] --- RIVER_TOP[RIVER_TOP]
    LANE_MID[LANE_MID] --- RIVER_ENTRY_RED_MID_TOP[RIVER_ENTRY_RED_MID_TOP]
    RIVER_ENTRY_RED_MID_TOP[RIVER_ENTRY_RED_MID_TOP] --- RIVER_TOP[RIVER_TOP]
    LANE_BOTTOM[LANE_BOTTOM] --- RIVER_ENTRY_BLUE_BOTTOM_LANE[RIVER_ENTRY_BLUE_BOTTOM_LANE]
    RIVER_ENTRY_BLUE_BOTTOM_LANE[RIVER_ENTRY_BLUE_BOTTOM_LANE] --- RIVER_BOTTOM[RIVER_BOTTOM]
    LANE_MID[LANE_MID] --- RIVER_ENTRY_BLUE_MID_BOTTOM[RIVER_ENTRY_BLUE_MID_BOTTOM]
    RIVER_ENTRY_BLUE_MID_BOTTOM[RIVER_ENTRY_BLUE_MID_BOTTOM] --- RIVER_BOTTOM[RIVER_BOTTOM]
    LANE_BOTTOM[LANE_BOTTOM] --- RIVER_ENTRY_RED_BOTTOM_LANE[RIVER_ENTRY_RED_BOTTOM_LANE]
    RIVER_ENTRY_RED_BOTTOM_LANE[RIVER_ENTRY_RED_BOTTOM_LANE] --- RIVER_BOTTOM[RIVER_BOTTOM]
    LANE_MID[LANE_MID] --- RIVER_ENTRY_RED_MID_BOTTOM[RIVER_ENTRY_RED_MID_BOTTOM]
    RIVER_ENTRY_RED_MID_BOTTOM[RIVER_ENTRY_RED_MID_BOTTOM] --- RIVER_BOTTOM[RIVER_BOTTOM]
    JUNGLE_BLUE_TOP[JUNGLE_BLUE_TOP] --- GATE_BLUE_TOP_LANE[GATE_BLUE_TOP_LANE]
    GATE_BLUE_TOP_LANE[GATE_BLUE_TOP_LANE] --- LANE_TOP[LANE_TOP]
    JUNGLE_BLUE_TOP[JUNGLE_BLUE_TOP] --- GATE_BLUE_TOP_RIVER[GATE_BLUE_TOP_RIVER]
    GATE_BLUE_TOP_RIVER[GATE_BLUE_TOP_RIVER] --- RIVER_TOP[RIVER_TOP]
    JUNGLE_BLUE_BOT[JUNGLE_BLUE_BOT] --- GATE_BLUE_BOT_LANE[GATE_BLUE_BOT_LANE]
    GATE_BLUE_BOT_LANE[GATE_BLUE_BOT_LANE] --- LANE_BOTTOM[LANE_BOTTOM]
    JUNGLE_BLUE_BOT[JUNGLE_BLUE_BOT] --- GATE_BLUE_BOT_RIVER[GATE_BLUE_BOT_RIVER]
    GATE_BLUE_BOT_RIVER[GATE_BLUE_BOT_RIVER] --- RIVER_BOTTOM[RIVER_BOTTOM]
    JUNGLE_RED_TOP[JUNGLE_RED_TOP] --- GATE_RED_TOP_LANE[GATE_RED_TOP_LANE]
    GATE_RED_TOP_LANE[GATE_RED_TOP_LANE] --- LANE_TOP[LANE_TOP]
    JUNGLE_RED_TOP[JUNGLE_RED_TOP] --- GATE_RED_TOP_RIVER[GATE_RED_TOP_RIVER]
    GATE_RED_TOP_RIVER[GATE_RED_TOP_RIVER] --- RIVER_TOP[RIVER_TOP]
    JUNGLE_RED_BOT[JUNGLE_RED_BOT] --- GATE_RED_BOT_LANE[GATE_RED_BOT_LANE]
    GATE_RED_BOT_LANE[GATE_RED_BOT_LANE] --- LANE_BOTTOM[LANE_BOTTOM]
    JUNGLE_RED_BOT[JUNGLE_RED_BOT] --- GATE_RED_BOT_RIVER[GATE_RED_BOT_RIVER]
    GATE_RED_BOT_RIVER[GATE_RED_BOT_RIVER] --- RIVER_BOTTOM[RIVER_BOTTOM]
    RIVER_TOP[RIVER_TOP] --- GATE_MORGARD_RIVER[GATE_MORGARD_RIVER]
    GATE_MORGARD_RIVER[GATE_MORGARD_RIVER] --- PIT_MORGARD[PIT_MORGARD]
    LANE_TOP[LANE_TOP] --- GATE_MORGARD_LANE[GATE_MORGARD_LANE]
    GATE_MORGARD_LANE[GATE_MORGARD_LANE] --- PIT_MORGARD[PIT_MORGARD]
    RIVER_BOTTOM[RIVER_BOTTOM] --- GATE_SERPEN_RIVER[GATE_SERPEN_RIVER]
    GATE_SERPEN_RIVER[GATE_SERPEN_RIVER] --- PIT_SERPEN[PIT_SERPEN]
    LANE_BOTTOM[LANE_BOTTOM] --- GATE_SERPEN_LANE[GATE_SERPEN_LANE]
    GATE_SERPEN_LANE[GATE_SERPEN_LANE] --- PIT_SERPEN[PIT_SERPEN]
    LANE_TOP[LANE_TOP] --- BASE_RED[BASE_RED]
    LANE_MID[LANE_MID] --- BASE_RED[BASE_RED]
    LANE_BOTTOM[LANE_BOTTOM] --- BASE_RED[BASE_RED]
