flowchart LR
    BASE_BLUE[BASE_BLUE] --- LANE_TOP[LANE_TOP]
    BASE_BLUE[BASE_BLUE] --- LANE_MID[LANE_MID]
    BASE_BLUE[BASE_BLUE] --- LANE_BOTTOM[LANE_BOTTOM]
    LANE_TOP[LANE_TOP] --- RIVER_TOP[RIVER_TOP]
    LANE_TOP[LANE_TOP] --- JUNGLE_BLUE_TOP[JUNGLE_BLUE_TOP]
    LANE_TOP[LANE_TOP] --- JUNGLE_RED_TOP[JUNGLE_RED_TOP]
    LANE_MID[LANE_MID] --- JUNGLE_BLUE_TOP[JUNGLE_BLUE_TOP]
    LANE_MID[LANE_MID] --- JUNGLE_BLUE_BOT[JUNGLE_BLUE_BOT]
    LANE_MID[LANE_MID] --- BRIDGE_MID[BRIDGE_MID]
    LANE_MID[LANE_MID] --- JUNGLE_RED_TOP[JUNGLE_RED_TOP]
    LANE_MID[LANE_MID] --- JUNGLE_RED_BOT[JUNGLE_RED_BOT]
    LANE_BOTTOM[LANE_BOTTOM] --- JUNGLE_BLUE_BOT[JUNGLE_BLUE_BOT]
    LANE_BOTTOM[LANE_BOTTOM] --- RIVER_BOTTOM[RIVER_BOTTOM]
    LANE_BOTTOM[LANE_BOTTOM] --- JUNGLE_RED_BOT[JUNGLE_RED_BOT]
    RIVER_TOP[RIVER_TOP] --- PIT_MORGARD[PIT_MORGARD]
    RIVER_TOP[RIVER_TOP] --- BRIDGE_MID[BRIDGE_MID]
    BRIDGE_MID[BRIDGE_MID] --- RIVER_BOTTOM[RIVER_BOTTOM]
    RIVER_BOTTOM[RIVER_BOTTOM] --- PIT_SERPEN[PIT_SERPEN]
    JUNGLE_BLUE_TOP[JUNGLE_BLUE_TOP] --- RIVER_TOP[RIVER_TOP]
    JUNGLE_BLUE_BOT[JUNGLE_BLUE_BOT] --- RIVER_BOTTOM[RIVER_BOTTOM]
    JUNGLE_RED_TOP[JUNGLE_RED_TOP] --- RIVER_TOP[RIVER_TOP]
    JUNGLE_RED_BOT[JUNGLE_RED_BOT] --- RIVER_BOTTOM[RIVER_BOTTOM]
    LANE_TOP[LANE_TOP] --- BASE_RED[BASE_RED]
    LANE_MID[LANE_MID] --- BASE_RED[BASE_RED]
    LANE_BOTTOM[LANE_BOTTOM] --- BASE_RED[BASE_RED]
